export const SET_LOCATION = 'SET_LOCATION'

export const TOGGLE_TIME_FORMAT = 'TOGGLE_TIME_FORMAT'
export const TOGGLE_SECONDS = 'TOGGLE_SECONDS'

export const REQUEST_TIME_ZONE = 'REQUEST_TIME_ZONE'
export const RECEIVE_TIME_ZONE = 'RECEIVE_TIME_ZONE'
export const REQUEST_TIME_ZONE_FAILURE = 'REQUEST_TIME_ZONE_FAILURE'

export const REQUEST_SUN = 'REQUEST_SUN'
export const RECEIVE_SUN = 'RECEIVE_SUN'
export const REQUEST_SUN_FAILURE = 'REQUEST_SUN_FAILURE'

export const TICK = 'TICK'
export const SAVE_TIMER_ID = 'SAVE_TIMER_ID'
